### ISSUE TITLE
TypeError: doc.pushToAlgolia is not a function   (mongoolia 1.0.3, mongoose 5.10)

### ISSUE THREAD

**Issue by fermaud** [algolia/mongoolia#12]
```
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
var algoliasearch = require('algoliasearch');
const mongoolia = require('mongoolia').default;

const VAR_ENV = require('../config.js');


const BookSchema = new Schema({
    title: {
        type: String,
        algoliaIndex: true,
        required: true,
        trim: true
    },
});

BookSchema.plugin(mongoolia, {
    appId: VAR_ENV.ALGOLIA_APP_ID,
    apiKey: VAR_ENV.ALGOLIA_API_KEY,
    indexName: VAR_ENV.ALGOLIA_PREFIX + '_BOOK',
    debug: true
})

const Book = mongoose.model('Book', BookSchema)

Book.syncWithAlgolia();

module.exports = Book;

```

**Comment by fermaud** [comment]
`const mongoose = require('mongoose');
const Schema = mongoose.Schema;
var algoliasearch = require('algoliasearch');
const mongoolia = require('mongoolia').default;

const VAR_ENV = require('../config.js');


const BookSchema = new Schema({
    title: {
        type: String,
        algoliaIndex: true,
        required: true,
        trim: true
    },
});

BookSchema.plugin(mongoolia, {
    appId: VAR_ENV.ALGOLIA_APP_ID,
    apiKey: VAR_ENV.ALGOLIA_API_KEY,
    indexName: VAR_ENV.ALGOLIA_PREFIX + '_BOOK',
    debug: true
})

const Book = mongoose.model('Book', BookSchema)

Book.syncWithAlgolia();

module.exports = Book;
`

**Comment by fermaud** [comment]
```
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
var algoliasearch = require('algoliasearch');
const mongoolia = require('mongoolia').default;

const VAR_ENV = require('../config.js');


const BookSchema = new Schema({
    title: {
        type: String,
        algoliaIndex: true,
        required: true,
        trim: true
    },
});

BookSchema.plugin(mongoolia, {
    appId: VAR_ENV.ALGOLIA_APP_ID,
    apiKey: VAR_ENV.ALGOLIA_API_KEY,
    indexName: VAR_ENV.ALGOLIA_PREFIX + '_BOOK',
    debug: true
})

const Book = mongoose.model('Book', BookSchema)

Book.syncWithAlgolia();

module.exports = Book;

```

**Comment by Sarath81198** [comment]
I'm also facing the same problem! Did you get any solution? @fermaud

**Comment by Sarath81198** [comment]
I'm also facing the same issue! Did you get any solution? @fermaud

**Comment by fermaud** [comment]
@Sarath81198 Yes i found two solutions: Using https://www.npmjs.com/package/mongoolia-v5 but it isnt real time sync ...
So i decided to use https://www.npmjs.com/package/mongoose-algolia because you have more features like virtuals or mappings.

For the sync I added a cron, wich every 30min, resync DB with SyncToAlgolia() from mongoose-algolia

**Comment by Sarath81198** [comment]
@fermaud I'll go with mongoose-algolia then.
